---
# tasks file for building_app
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: install packages
    apt:
      pkg:
      - default-jdk
      - git
      - maven

  - name: Git clone project
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /tmp/boxfuse
      clone: yes
      update: yes

  - name: This command will change the working directory to tmp/boxfuse and for maven packege.
    shell:
      cmd: mvn -f /tmp/boxfuse/pom.xml package
      chdir: /tmp/boxfuse

  - name: Synchronization of src on the inventory host to the dest on the localhost in pull mode
    synchronize:
      mode: pull
      src: /tmp/boxfuse/target/hello-1.0.war
      dest: /tmp/boxfuse/

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
